---
# Install Docker on the "Metrics Server" and other pre-configuration
- hosts: metrics_server
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
  - { role: install_docker_debian }
  - { role: config_mc_srv_pre }

# Configuration on DSE servers
- hosts: dse_server
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
  - { role: config_dse_srv }

# Post-configuration on the "Metrics Server"
- hosts: metrics_server
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
  - { role: config_mc_srv_post }